-- Create the posts table
create table posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  content text,
  image_url text,
  published boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table posts enable row level security;

-- Create a policy that allows anyone to read published posts
-- Note: For simplicity in this initial setup, we might allow reading all posts, 
-- but ideally we filter by published = true for public API.
-- However, since we want to see drafts in the admin panel, we need a way to distinguish.
-- Usually, we allow public read access to everything for now, and filter in the frontend for public views.
create policy "Enable read access for all users"
on posts for select
using (true);

-- Create a policy that allows only authenticated users to insert/update/delete
create policy "Enable insert for authenticated users only"
on posts for insert
to authenticated
with check (true);

create policy "Enable update for authenticated users only"
on posts for update
to authenticated
using (true);

create policy "Enable delete for authenticated users only"
on posts for delete
to authenticated
using (true);

-- Create a bucket for blog images
insert into storage.buckets (id, name, public)
values ('blog-images', 'blog-images', true);

-- Allow public access to blog images
create policy "Give public access to blog images"
on storage.objects for select
using ( bucket_id = 'blog-images' );

-- Allow authenticated users to upload images
create policy "Allow authenticated uploads"
on storage.objects for insert
to authenticated
with check ( bucket_id = 'blog-images' );
